### PR TITLE
set version 1.4.0: add tooltip property to TestSuiteInfo and TestInfo

### PR DESCRIPTION
**Pull request by matepek**
If you accepted this pull request I would create the counterpart too for Test Explorer.

I would use this field to give more info about the suites and tests. For example: executable path; test name (it would be helpful when the label is too long)

### CODE REVIEW

**Comment by matepek** [comment]
I've just noticed this [issue](https://github.com/hbenl/vscode-test-explorer/issues/25).
So `description` could be useful too. 
It requires vscode version 1.30.

And `TestSuiteInfo`'s label could be `string | vscode.Uri` type.
And then `description` could be work like in [TreeView](https://code.visualstudio.com/updates/v1_30#_custom-views) `description?: string | boolean;`
I checked the Test Explorer's code, it would work with the extended label type too.

```
export interface TestSuiteInfo {

	type: 'suite';

	id: string;

	/** 
	 * The label to be displayed by the Test Explorer for this suite.
	 * It can be a `vscode.Uri` in which case the description can be generated.
	 * */
	label: string | vscode.Uri;

	/**
	 * A human readable string which is rendered less prominent.
	 * When `true`, it is derived from `label` and when `falsy`, it is not shown.
	 * See `vscode.TreeItem`'s for details.
	 */
	description?: string | boolean;

	/** The tooltip text when you hover over this suite. */
	tooltip?: string;

	/**
	 * The file containing this suite (if known).
	 * This can either be an absolute path (if it is a local file) or a URI.
	 * Note that this should never contain a `file://` URI.
	 */
	file?: string;

	/** The line within the specified file where the suite definition starts (if known). */
	line?: number;

	children: (TestSuiteInfo | TestInfo)[];
}

/**
 * Information about a test.
 */
export interface TestInfo {

	type: 'test';

	id: string;

	/** The label to be displayed by the Test Explorer for this test. */
	label: string;

	/** A human readable string which is rendered less prominent. */
	description?: string;

	/** The tooltip text when you hover over this test. */
	tooltip?: string;

	/**
	 * The file containing this test (if known).
	 * This can either be an absolute path (if it is a local file) or a URI.
	 * Note that this should never contain a `file://` URI.
	 */
	file?: string;

	/** The line within the specified file where the test definition starts (if known). */
	line?: number;

	/** Indicates whether this test will be skipped during test runs */
	skipped?: boolean;
}
```

Let me know if you agree and I can extend my pull request.

**Comment by hbenl** [comment]
I have added the tooltip to the API and the Test Explorer.
By the way, I prefer to set the package version in a separate commit when I publish. This way it's always clear which commit got published if I add more changes after merging a PR.

**Comment by hbenl** [comment]
I've been thinking about adding `description` as well, but I think the `description` could also be a good place for extra info that the user can configure, some users may want to see the filename, others a summary of the test states under this node (e.g. "5 passed, 1 failed") or the time it took for the test(s) to run... so I'm simply not sure yet what I'll use `TreeItem#description` for.

About allowing `vscode.Uri` for the label: I'm currently trying to make my Mocha Adapter testable and noticed that having any `vscode` dependencies creates problems because the code will only run in an Extension Host (and the testing experience in that case is horrible). So I'm separating most of the adapter code into an adapter "core" without `vscode` dependencies. That looks very promising, but it would not be possible to avoid `vscode` dependencies in the core if `TestInfo` and/or `TestSuiteInfo` contain `vscode` dependencies...

**Comment by matepek** [comment]
About __description__: That is actually a great idea. I would like to see the running time there!

I have an idea in which case both of the cases works:
Adding a `description?: string` to TestSuiteInfo, TestInfo, TestSuiteEvent and TestEvent.
Initially TreeItem#description is filled with TestSuiteInfo's and TestInfo's description if provided and would be overwritten by the event's description property if provided.

About `vscode.Uri`:
I wouldn't use it anyway, so don't think that I'm clinging on this, just sharing a possible solution.
There could be an
```
export class ConvertToUri { path:string }
```
class and the Test Explorer could check the type (`instanceof ConvertToUri`) and create the vscode.Uri. In this case TestSuiteInfo's description should be `string | boolean`.

**Pull request closed without merging**
